/**
 * Sushi Klassiek menu data
 * Source: https://www.sushiklassiek.nl/
 */

const RESTAURANT = {
  name: 'Sushi Klassiek',
  tagline: 'Welkom Online bestellen bij Sushi Klassiek in Amsterdam!',
  address: 'Commelinstraat 292',
  postal: '1093VD Amsterdam',
  phone: '0686450614',
  phoneDisplay: '06 8645 0614',
  email: 'info@sushiklassiek.nl',
  rating: 4,
  reviewCount: 9,
  discountThreshold: 20,
  discountPercent: 10,
  deliveryFee: 2.5,
  minDelivery: 15,
  minPickup: 0,
  pointsPerEuro: 25,
};

/** Opening hours: start/end in minutes from midnight. end < start means crosses midnight. */
const OPENING_HOURS = [
  { day: 1, label: 'Maandag', start: 16 * 60, end: 22 * 60 },
  { day: 2, label: 'Dinsdag', start: 19 * 60, end: 1 * 60 },
  { day: 3, label: 'Woensdag', start: 16 * 60, end: 1 * 60 },
  { day: 4, label: 'Donderdag', start: null, end: null, closed: true },
  { day: 5, label: 'Vrijdag', start: 16 * 60, end: 1 * 60 },
  { day: 6, label: 'Zaterdag', start: 16 * 60, end: 1 * 60 },
  { day: 0, label: 'Zondag', start: 16 * 60, end: 1 * 60 },
];

const DELIVERY_AREAS = [
  { name: 'Amsterdam Centrum', postcodes: '1011–1018', min: 20, time: '30–45 min' },
  { name: 'Amsterdam Oost', postcodes: '1091–1095', min: 15, time: '25–40 min' },
  { name: 'Amsterdam Noord', postcodes: '1021–1037', min: 25, time: '35–50 min' },
  { name: 'Amsterdam West', postcodes: '1051–1069', min: 20, time: '30–45 min' },
];

const REVIEWS = [
  {
    name: 'Lisa M.',
    rating: 5,
    date: '12 jan 2026',
    text: 'Heerlijke sushi, altijd vers en snel bezorgd. De Mix Box is een absolute aanrader!',
  },
  {
    name: 'Tom van D.',
    rating: 4,
    date: '3 feb 2026',
    text: 'Goede kwaliteit voor een eerlijke prijs. Poke Bowl was top, alleen iets langer wachten op drukke avonden.',
  },
  {
    name: 'Sophie K.',
    rating: 5,
    date: '18 feb 2026',
    text: 'Beste sushi in de buurt. Flamed Salmon rolls zijn fantastisch. Online bestellen werkt super soepel.',
  },
  {
    name: 'Ahmed R.',
    rating: 4,
    date: '1 mrt 2026',
    text: 'Nette porties en vriendelijke service. De 10% korting via de website is een mooie bonus.',
  },
  {
    name: 'Emma J.',
    rating: 4,
    date: '15 mrt 2026',
    text: 'Lekker en fris. Special Rolls Dragon Fly is mijn favoriet. Zeker een aanrader!',
  },
];

const IMG = {
  hero: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg',
  fallback: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg',
};

const MENU = [
  {
    id: 'nigri',
    name: 'Nigri',
    items: [
      { id: 'nigri-salmon', name: 'Salmon', price: 1.75, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57c268829d_WhatsApp_Image_2026-02-18_at_23.png', popular: false },
      { id: 'nigri-tona', name: 'Tona', price: 2.25, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57c46cb857_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'nigri-avocado', name: 'Avocado', price: 1.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f96ada4af44_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'nigri-flamed-salmon', name: 'Flamed Salmon', price: 2.25, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f96b252dea4_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'nigri-flamed-tona', name: 'Flamed Tona', price: 2.75, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f96bbaa731b_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'nigri-ebi', name: 'Ebi', price: 1.75, tags: ['Schaal- en schelpdieren'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67fa19613afc2_WhatsApp_Image_2025-04-12_at_08.png', popular: false },
    ],
  },
  {
    id: 'gunkan',
    name: 'Gunkan',
    items: [
      { id: 'gunkan-salmon', name: 'Salmon', price: 3.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68013fc0924c8_edit.png', popular: false },
      { id: 'gunkan-tona', name: 'Tona', price: 5.0, tags: ['Vis'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'gunkan-tobico', name: 'Tobico', price: 5.0, tags: ['Schaal- en schelpdieren'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'gunkan-flamed-salmon', name: 'Flamed Salmon', price: 4.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68013fd62e3b8_edit_2.png', popular: false },
    ],
  },
  {
    id: 'maki',
    name: 'Maki',
    items: [
      { id: 'maki-salmon', name: 'Salmon (8 stuks)', price: 6.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794eee19108_salmon_maki.png', popular: false },
      { id: 'maki-tona', name: 'Tona (8 stuks)', price: 6.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f8e7e07b191_WhatsApp_Image_2025-04-06_at_22.png', popular: false },
      { id: 'maki-chuka', name: 'Chuka Wakame (8 stuks)', price: 4.25, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794f2d4b8a3_chukawakame_maki.png', popular: false },
      { id: 'maki-crub', name: 'Crub (8 stuks)', price: 4.25, tags: ['Schaal- en schelpdieren'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795d0caaf07_crap_maki.png', popular: false },
      { id: 'maki-avocado', name: 'Avocado (8 stuks)', price: 4.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794f4620a82_WhatsApp_Image_2025-07-17_at_21.png', popular: false },
    ],
  },
  {
    id: 'crispy',
    name: 'Crispy',
    items: [
      { id: 'crispy-karaage', name: 'Karaage (4 stuks)', price: 5.5, tags: ['Mild', 'Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57c9254814_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-chicken-spring', name: 'Chicken Mini Spring Roll (4 stuks)', price: 5.0, tags: ['Mild', 'Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a834219db3a_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-veg-spring', name: 'Vegetable Mini Spring Roll (4 stuks)', price: 4.0, tags: ['Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a8345e152be_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-ebi', name: 'Ebi (4 stuks)', price: 6.5, tags: ['Mild', 'Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57d05422d9_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-gioza-chicken', name: 'Gioza chicken', price: 3.0, tags: [], desc: '4 stuks', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57d302c7a4_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-gioza-beef', name: 'Gioza Beef 4 stuk', price: 3.5, tags: [], desc: '4 STUK', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6879967704698_WhatsApp_Image_2025-07-17_at_23.png', popular: false },
      { id: 'crispy-gioza-veg', name: 'Gioza vegetabel 4 stuk', price: 2.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/687996b5cb4e4_WhatsApp_Image_2025-07-17_at_23.png', popular: false },
      { id: 'crispy-gioza-shrimp', name: 'Shirmp Gioza 4 stuks', price: 3.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57d5cbcb1c_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-fish-finger', name: 'Fish Finger 4 stuk', price: 2.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/687998592603c_WhatsApp_Image_2025-07-17_at_23.png', popular: false },
      { id: 'crispy-squid', name: 'Fried Squid Rings', price: 2.75, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a833f751dad_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'crispy-kaas', name: 'Mini Kaassouffles (mini cheese souffles)', price: 4.75, tags: ['Melk'], desc: '6 stuks', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688c4b92ca6_WhatsApp_Image_2026-07-28_at_12.png', popular: false },
      { id: 'crispy-prawn-crackers', name: 'Prawn crackers', price: 1.75, tags: [], desc: 'one portion', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688cca7103e_3.png', popular: false },
    ],
  },
  {
    id: 'steam',
    name: 'Steam',
    items: [
      { id: 'steam-edamame', name: 'Edamame', price: 3.5, tags: ['Sesam'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794f65bfe6d_edamame.png', popular: false },
      { id: 'steam-chuka', name: 'Chuka Wakame', price: 3.5, tags: ['Sesam', 'Sulfiet'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794f76e6b77_chukawame.png', popular: false },
      { id: 'steam-spicy-edamame', name: 'Spicy Steam Edamame', price: 3.75, tags: ['Veganistisch', 'Halal'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794f8dbb028_WhatsApp_Image_2025-07-17_at_21.png', popular: false },
    ],
  },
  {
    id: 'sashimi',
    name: 'Sashimi',
    items: [
      { id: 'sashimi-salmon', name: 'Salmon (4 stuks)', price: 6.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a834b923e05_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'sashimi-tona', name: 'Tona (4 stuks)', price: 6.75, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a834e70c93e_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'sashimi-flamed-salmon', name: 'Flamed Salmon (4 stuks)', price: 6.0, tags: ['Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a834b923e05_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
    ],
  },
  {
    id: 'fried-rolls',
    name: 'Fried Rolls',
    items: [
      { id: 'fried-salmon', name: 'Salmon (8 stuks)', price: 12.0, tags: ['Schaal- en schelpdieren', 'Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a57bd9c599a_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'fried-chicken', name: 'Chicken (8 stuks)', price: 12.0, tags: ['Mild', 'Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68794fc93dac2_chicken_fried_roll.png', popular: false },
      { id: 'fried-veggie', name: 'Veggie (8 stuks)', price: 7.0, tags: [], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
    ],
  },
  {
    id: 'temaki',
    name: 'Temaki',
    items: [
      { id: 'temaki-ebi', name: 'Ebi', price: 4.25, tags: ['Gluten', 'Schaal- en schelpdieren', 'Sesam'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'temaki-california', name: 'California', price: 4.25, tags: ['Schaal- en schelpdieren', 'Sesam'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'temaki-tempura-ebi', name: 'Tempura Ebi', price: 4.25, tags: ['Mild', 'Gluten', 'Schaal- en schelpdieren', 'Sesam'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'temaki-crispy-chicken', name: 'Crispy Chicken', price: 5.0, tags: ['Gluten', 'Sesam'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83ce68131a_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'temaki-tona', name: 'Tona', price: 7.0, tags: ['Sesam', 'Vis'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
    ],
  },
  {
    id: 'roll-urumaki',
    name: 'Roll Urumaki',
    items: [
      { id: 'urumaki-california', name: 'California (8 stuks)', price: 7.75, tags: ['Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f985936119d_WhatsApp_Image_2025-04-11_at_22.png', popular: false },
      { id: 'urumaki-tempura-ebi', name: 'Tempura Ebi (8 stuks)', price: 10.0, tags: ['Mild', 'Ei', 'Gluten', 'Schaal- en schelpdieren', 'Sesam'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795e01d53d4_tempura_ebi.png', popular: false },
      { id: 'urumaki-tona', name: 'Tona (8 stuks)', price: 12.0, tags: ['Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f980592d16c_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'urumaki-spicy-tona', name: 'Spicy Tona (8 stuks)', price: 12.0, tags: ['Pittig', 'Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f980592d16c_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'urumaki-spicy-ebi', name: 'Spicy Ebi (8 stuks)', price: 12.0, tags: ['Pittig', 'Ei', 'Gluten', 'Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f980592d16c_WhatsApp_Image_2025-04-11_at_20.png', popular: false },
      { id: 'urumaki-crispy-chicken', name: 'Crispy Chicken (8 stuks)', price: 8.0, tags: ['Gluten'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/687950f071da1_chicken_fried_roll.png', popular: false },
      { id: 'urumaki-salmon', name: 'Salmon (8 stuks)', price: 11.0, tags: ['Schaal- en schelpdieren', 'Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a8367d6e1b5_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
    ],
  },
  {
    id: 'special-rolls',
    name: 'Special Rolls',
    items: [
      { id: 'special-salmon', name: 'Salmon (8 stuks)', price: 12.75, tags: ['Sesam', 'Vis'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a8364b5434b_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'special-salmon-avo', name: 'Salmon Avocado (8 stuks)', price: 12.75, tags: ['Ei', 'Sesam', 'Vis', 'Sulfiet'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a837b7e9c77_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'special-flamed-salmon', name: 'Flamed Salmon (8 stuks)', price: 12.75, tags: ['Mild', 'Ei', 'Sesam', 'Vis', 'Sulfiet'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f8e21e6b166_WhatsApp_Image_2025-04-06_at_22.png', popular: false },
      { id: 'special-ebi-avo', name: 'Ebi Avocado (8 stuks)', price: 12.75, tags: ['Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Sulfiet'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a835bc986d2_WhatsApp_Image_2026-02-18_at_10.png', popular: false },
      { id: 'special-cali-avo', name: 'California Avocado (8 stuks)', price: 12.75, tags: ['Schaal- en schelpdieren', 'Sesam'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'special-dragon', name: 'Dragon Fly (8 stuks)', price: 12.75, tags: ['Mild', 'Ei', 'Schaal- en schelpdieren', 'Sesam', 'Vis', 'Sulfiet'], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67f8e3886742f_WhatsApp_Image_2025-04-06_at_22.png', popular: false },
      {
        id: 'special-tona-caviar',
        name: 'Tona with Black caviar',
        price: 15.75,
        tags: ['Ei', 'Vis', 'Halal'],
        desc: 'sushi rice, tona, cucumber, avocado, caviar',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/682bb1590b8ff_tona_with_black_c_imresizer.png',
        popular: false,
      },
      {
        id: 'special-strawberry',
        name: 'Strawberry Roll',
        price: 12.5,
        tags: [],
        desc: 'philadelphia cheese, sushi rice, strawberry, salmon, strawberry sauce, seasome',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6872bd064eb98_strawberry_roll.png',
        popular: false,
      },
    ],
  },
  {
    id: 'boxes',
    name: 'Boxes',
    items: [
      {
        id: 'box-mix-s',
        name: 'Mix Box S (16 stuks)',
        price: 20.0,
        tags: ['Mild', 'Ei', 'Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: 'Ebi Roll (4), Salmon Roll (4), tuna roll (4), Spring roll (2), Eby fry (2)',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83c8ceae47_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
      {
        id: 'box-mix-s2',
        name: 'Mix Box S 2 (16 stuks)',
        price: 12.0,
        tags: ['Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: 'fried chicken Roll (8 stuks), salmon roll (8 stuks)',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83800acf88_WhatsApp_Image_2026-02-18_at_10.png',
        popular: true,
      },
      {
        id: 'box-mix-m',
        name: 'Mix roll box M 24 STUKS',
        price: 24.0,
        tags: ['Mild', 'Ei', 'Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: '8 STUK SALMON ROLL, 8 STUK EBI TEMPURA ROLL, 8 STUK CALIFORNIA ROLL',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6802a20cedaae_mix_box_24_stuks_resize.png',
        popular: true,
      },
      {
        id: 'box-mix-xxl',
        name: 'Mix Box XXL (56 stuks)',
        price: 50.0,
        tags: ['Mild', 'Ei', 'Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: 'Ebi Roll (8), Fried Salmon Roll (8), Salmon Roll (8), California Roll (8), Tona Roll (8), Salmon Nigri (2), Tona Nigri (2), Avocado Maki (8), Ebi Fryer (2), Spring Roll (2)',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83a36d2505_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
      {
        id: 'box-craving',
        name: 'Craving Box (16 stuks)',
        price: 12.0,
        tags: ['Mild', 'Ei', 'Gluten', 'Sesam', 'Vis'],
        desc: 'Fried Chicken Roll (8), Salmon Roll (4), California Roll (4)',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83ae72a24b_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
      {
        id: 'box-mix-m21',
        name: 'Mix box M 21pic',
        price: 24.5,
        tags: ['Ei', 'Gluten', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: 'Salmon roll 4, Salmon maki 4, fry Ebi 1, spring roll 3, fry salmon roll 7, Salmon nigri 2',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83ba7b8f02_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
      {
        id: 'box-fried-salmon',
        name: 'Fried Salmon Roll 8 stuks',
        price: 12.0,
        tags: [],
        desc: 'sushi rice, salmon, spicy mayo, tempura',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83ab99bc40_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
    ],
  },
  {
    id: 'poke-bowls',
    name: 'Poke Bowls',
    items: [
      {
        id: 'poke-salmon',
        name: 'Salmon Poke Bowl',
        price: 12.0,
        tags: ['Mild', 'Ei', 'Schaal- en schelpdieren', 'Sesam'],
        desc: 'Sushi rice, Cucumber, Lettuce, Salmon, Mango, Green beans, Tobico, Spicy mayo, Teriyaki sauce',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83bf221def_WhatsApp_Image_2026-02-18_at_10.png',
        popular: true,
      },
      {
        id: 'poke-tona',
        name: 'Tona Poke Bowl',
        price: 12.5,
        tags: ['Mild', 'Ei', 'Schaal- en schelpdieren', 'Sesam', 'Vis'],
        desc: 'Sushi rice, Cucumber, lettuce, Tona, Green beans, Tobico, Spicy mayo, Teriyaki sauce',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/69a83c481442f_WhatsApp_Image_2026-02-18_at_10.png',
        popular: false,
      },
      {
        id: 'poke-salad',
        name: 'Salad',
        price: 3.75,
        tags: ['Ei', 'Mosterd', 'Sesam', 'Veganistisch'],
        desc: 'Mix vegetable with truffel mayonaise, teriyaki sauce, sesame',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67fd3c8ca6698_WhatsApp_Image_2025-04-14_at_18.png',
        popular: false,
      },
      {
        id: 'poke-veggie',
        name: 'Poke Bowl veggie',
        price: 7.99,
        tags: ['Sesam', 'Soja', 'Veganistisch', 'Halal'],
        desc: 'sushi rice, avocado, lettuce, mango, strawberry, sesame',
        image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/67fed1487694c_poke_bowl_veggi_imresizer.png',
        popular: false,
      },
    ],
  },
  {
    id: 'cold-drinks',
    name: 'Cold Drinks',
    items: [
      { id: 'drink-cola', name: 'Cocacola', price: 2.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160a5b8ff6_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-redbull', name: 'Red Bull', price: 3.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160bb717e6_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-fuze', name: 'Fuze Tea', price: 3.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160caa55b6_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-cola-zero', name: 'Cocacola zero', price: 2.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160e9b4700_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-water', name: 'Water', price: 2.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160f687547_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-lychee', name: 'Foco Lychee Drink', price: 3.5, tags: [], desc: '350ml', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686161036230d_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-coconut', name: 'Foco Roasted Coconut Juice', price: 3.5, tags: [], desc: '350ml', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686161144af1b_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-mangajo-pom', name: 'Mangajo pomegranate and Green Tea', price: 3.75, tags: [], desc: '250ML', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686161258ee9c_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-mangajo-yuzu', name: 'Mangajo Yuzu and Lemon Juice', price: 3.75, tags: [], desc: '250ml', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68616131a0e92_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-foco-mango', name: 'Foco Mango Juice', price: 3.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/686160caa55b6_WhatsApp_Image_2025-06-29_at_17.png', popular: false },
      { id: 'drink-rubicon-guava', name: 'Rubicon Guava Nektar', price: 3.75, tags: [], desc: '1 liter', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688e0e09dbe_7.png', popular: false },
      { id: 'drink-rubicon-lychee', name: 'Rubicon Lychee Juice', price: 3.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688e5147c57_5.png', popular: false },
      { id: 'drink-rubicon-mango', name: 'Rubicon Mango Juice', price: 3.75, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688e9fafa17_8.png', popular: false },
      { id: 'drink-sprite', name: 'Spirte', price: 2.75, tags: [], desc: '500ml', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688f003b296_4.png', popular: false },
    ],
  },
  {
    id: 'extra',
    name: 'Extra',
    items: [
      { id: 'extra-soy', name: 'soy sauce', price: 0.5, tags: [], desc: '20ml', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/687950102b612_WhatsApp_Image_2025-07-05_at_19.png', popular: false },
      { id: 'extra-wasabi', name: 'wasabi', price: 0.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795041ec660_WhatsApp_Image_2025-07-05_at_19.png', popular: false },
      { id: 'extra-ginger', name: 'ginger pickel', price: 0.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/687950c5b40fc_WhatsApp_Image_2025-07-05_at_19.png', popular: false },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    items: [
      { id: 'dessert-cheesecake', name: 'Cheesecake 4 pieces', price: 3.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795b7feed16_WhatsApp_Image_2025-06-13_at_19.png', popular: false },
      { id: 'dessert-raspberry', name: 'Red Raspberry mini cake 4 stuks', price: 4.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795c27a0ff9_WhatsApp_Image_2025-06-13_at_19.png', popular: false },
      { id: 'dessert-rainbow', name: 'Rainbow mini cake 4 pieces', price: 4.0, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/68795c57c16a8_WhatsApp_Image_2025-06-13_at_19.png', popular: false },
      { id: 'dessert-brownie', name: 'Brownie Funky Nuts', price: 4.5, tags: ['Noten', 'Pinda\'s'], desc: '', image: 'https://www.sushiklassiek.nl/algemeen/img/photos/sorted/oosters/sushi/sushi5.jpg', popular: false },
      { id: 'dessert-bj-strawberry', name: 'Ben And Jerry mini strawberry cheesecake', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b7d8e96cfa_5.png', popular: false },
      { id: 'dessert-bj-caramel', name: 'Ben And Jerry mini caramel chew chew', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b7ec6cb79d_8.png', popular: false },
      { id: 'dessert-bj-fudge', name: 'Ben and jerry chocolate fudge brownie', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b7f237f416_9.png', popular: false },
      { id: 'dessert-bj-cookie', name: 'Ben and jerry mini cookie dough', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b7f7745524_6.png', popular: false },
      { id: 'dessert-bj-sandwich', name: 'Ben and jerry cookie dough sandwitch', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b7fd52569c_10.png', popular: false },
      { id: 'dessert-magnum-gold', name: 'Magnum Gold Billionaire Bar', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b803310313_packshot-thumbnail.png', popular: false },
      { id: 'dessert-magnum-almond', name: 'Magnum sandwitch almond', price: 4.5, tags: [], desc: '', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a5b808ea8045_7.png', popular: false },
      { id: 'dessert-fortune', name: 'Fortune Coockies', price: 1.75, tags: [], desc: '2 stuks', image: 'https://cdn.sitedish.nl/www.sushiklassiek.nl/img/gerechten/6a688f5279c7e_6.png', popular: false },
    ],
  },
];
